# Generated by scripts/update-cask.sh. Do not edit manually.
# No zap stanza: the app keeps no persistent user files outside the app
# bundle itself, so there is nothing to clean up on uninstall.
cask "lanterna" do
  version "0.6.4"
  sha256 "3e78d09af754b61ebb75fdaf7cb6443935a43c56e1c19940c13b4eddeebd0173"

  url "https://github.com/peacock0803sz/Lanterna/releases/download/v0.6.4/Lanterna-0.6.4.dmg",
      verified: "github.com/peacock0803sz/Lanterna/"
  name "Lanterna"
  desc "List-style window switcher for macOS"
  homepage "https://github.com/peacock0803sz/Lanterna"

  depends_on macos: :tahoe
  depends_on arch: :arm64

  app "Lanterna.app"
end
