/// Generated by scripts/generate-version.sh from the release tag. Do not edit.
enum AppVersion {
    /// The full describe string, for on-screen display.
    static let full = "v0.2.0"
    /// The normalized X.Y.Z, for the bundle Info.plist.
    static let short = "0.2.0"
}
