#!/usr/bin/env bash
# Writes Sources/Lanterna/Support/Version.swift from the release tag.
#
# The tag must be exactly `vX.Y.Z` on a clean tree: anything else (a commit
# past the tag, a dirty tree, no tag at all) is a refusal, not a fallback.
# There is no fallback version string anywhere in this project, so a build
# that cannot name its release does not happen.
#
# Usual builds never run this: the generated file is committed, and only the
# release bootstrap (quickstart procedure 6) and package-app.sh call it.
set -euo pipefail

cd "$(dirname "$0")/.."

describe=$(git describe --tags --dirty 2>/dev/null) || {
    echo "generate-version: no tag found; tag the release first (vX.Y.Z)" >&2
    exit 1
}

if [[ ! $describe =~ ^v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
    echo "generate-version: refusing \"$describe\"; need exactly vX.Y.Z on a clean tree" >&2
    exit 1
fi

short="${BASH_REMATCH[1]}"

cat > Sources/Lanterna/Support/Version.swift <<EOF
/// Generated by scripts/generate-version.sh from the release tag. Do not edit.
enum AppVersion {
    /// The full describe string, for on-screen display.
    static let full = "$describe"
    /// The normalized X.Y.Z, for the bundle Info.plist.
    static let short = "$short"
}
EOF

echo "generate-version: wrote $describe / $short"
