#!/usr/bin/env bash
# Generates or updates Casks/lanterna.rb from a version and a DMG checksum.
#
# Usage: bash scripts/update-cask.sh <X.Y.Z> <sha256>
#
# The cask points at the DMG attached to the GitHub Release of the same
# version. Run it after the DMG is built so the checksum is the measured one,
# never a placeholder.
set -euo pipefail

cd "$(dirname "$0")/.."

version="${1:?usage: update-cask.sh <X.Y.Z> <sha256>}"
sha="${2:?usage: update-cask.sh <X.Y.Z> <sha256>}"

if [[ ! $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "update-cask: refusing version \"$version\"; need exactly X.Y.Z (no v prefix)" >&2
    exit 1
fi
if [[ ! $sha =~ ^[0-9a-f]{64}$ ]]; then
    echo "update-cask: refusing sha256; need 64 lowercase hex characters" >&2
    exit 1
fi

mkdir -p Casks

cat > Casks/lanterna.rb <<EOF
# Generated by scripts/update-cask.sh. Do not edit manually.
# No zap stanza: the app keeps no persistent user files outside the app
# bundle itself, so there is nothing to clean up on uninstall.
cask "lanterna" do
  version "${version}"
  sha256 "${sha}"

  url "https://github.com/peacock0803sz/Lanterna/releases/download/v${version}/Lanterna-${version}.dmg",
      verified: "github.com/peacock0803sz/Lanterna/"
  name "Lanterna"
  desc "List-style window switcher for macOS"
  homepage "https://github.com/peacock0803sz/Lanterna"

  depends_on macos: :tahoe
  depends_on arch: :arm64

  app "Lanterna.app"
end
EOF

echo "update-cask: wrote Casks/lanterna.rb ($version)"
